### ISSUE TITLE
Покупка "На n секунд даётся m печенек за клик"

### ISSUE THREAD

**Issue by segamolder** [Catling10/cookieclicker#5]
Собственно все в описании. В двух словах нам нужно добавить переменную (если ее еще нет), сколько даётся печенек за клик.
При покупке задавать переменной увеличенное значение, сразу после задать тайм-аут через который уменьшить это значение

**Comment by Catling10** [comment]
Сделал чуть иначе (ну прост с точки зрения сохранения смысла апгрейда при развитии), на n секунд даётся x2 печенек за клик
